version: '3'
services:
  weather:
    build: ./weather
    ports:
      - "8111:8111"
    image: "weather:0.4.0"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.17
  rbc:
    build: ./rbc
    ports:
      - "8110:8110"
    image: "rbc:0.9.0"
    depends_on:
      - dbpostgresql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.18
  predict:
    build: ./predict
    ports:
      - "8113:8113"
    image: "predict:0.3.0"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.20

  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: adminadmin
      POSTGRES_PASSWORD: pwdpwd
    networks:
      vpcbr:
        ipv4_address: 10.5.0.19

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - dbpostgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    networks:
      vpcbr:
        ipv4_address: 10.5.0.21
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      vpcbr:
        ipv4_address: 10.5.0.22

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.16/24


