global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'weather_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['weather:8111']
  - job_name: 'rbc_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['rbc:8110']
  - job_name: 'predict_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['predict:8113']