apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predict
  template:
    metadata:
      name: predict
      labels:
        app: predict
    spec:
      containers:
        - name: predict
          env:
          image: predict:0.3.0
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: predict
spec:
  ports:
    - port: 8113
      targetPort: 8113
  selector:
    app: predict
  type: LoadBalancer