version: '3'
services:
  rbc:
    build: ./rbc
    ports:
      - "8110:8110"
    image: "rbc:0.9.0"
    depends_on:
      - dbpostgresql
  

  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5052:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: adminadmin
      POSTGRES_PASSWORD: pwdpwd


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - dbpostgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
